Update toc.yml
project-origin/registry pull request #100
Opened 2023-03-29 12:24 UTC by wisbech

The overview article should now be available in the github.io docs

2023-03-31 05:55 UTC, lauranolling approved these changes

2023-03-31 06:45 UTC, MartinSchmidt requested changes

2023-03-31 06:45 UTC, MartinSchmidt commented on doc/concept/toc.yml
> +- name: Registrys
plural of registry is registries

2023-04-13 11:58 UTC, wisbech commented on doc/concept/toc.yml
> +- name: Registrys
You are right

2023-04-17 09:19 UTC, wisbech reviewed
@lauranolling would you be awesome and approve this PR

2023-04-18 07:26 UTC, MartinSchmidt approved these changes

2023-05-01 07:42 UTC, merged